<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildProjectDirectory)\..\Alliance.Common\CommonProps.props" />

	<PropertyGroup>
    <Version>$(AllianceVersion)</Version>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<ModuleId>$(MSBuildProjectName)</ModuleId>
		<ModuleName>Alliance.Editor</ModuleName>
		<GameFolder>$(BANNERLORD_GAME_DIR)</GameFolder>
		<UseWPF>true</UseWPF>
		<OutputType>Library</OutputType>
		<DefineConstants>$(DefineConstants);_RGL_KEEP_ASSERTS</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.*.dll" Exclude="$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Native.dll">
			<HintPath>%(Identity)</HintPath>
		</Reference>
		<Reference Include="$(GameFolder)\Modules\Native\bin\Win64_Shipping_Client\*.dll">
			<HintPath>%(Identity)</HintPath>
		</Reference>
		<Reference Include="$(GameFolder)\Modules\CustomBattle\bin\Win64_Shipping_wEditor\*.dll">
			<HintPath>%(Identity)</HintPath>
		</Reference>
		<Reference Include="$(GameFolder)\bin\Win64_Shipping_Client\System.Numerics.Vectors.dll">
			<HintPath>%(Identity)</HintPath>
		</Reference>
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Alliance.Common\Alliance.Common.csproj" />
	</ItemGroup>
	
	<ItemGroup>
	  <Resource Include="Resources\alliance_delete.png" />
	  <Resource Include="Resources\alliance_edit.png" />
	  <Resource Include="Resources\alliance_edit2.png" />
	  <Resource Include="Resources\alliance_help.png" />
	  <Resource Include="Resources\alliance_help2.png" />
	  <Resource Include="Resources\alliance_ico.ico" />
	  <Resource Include="Resources\alliance_info.png" />
	  <Resource Include="Resources\alliance_manual.png" />
	  <Resource Include="Resources\alliance_save.png" />
	  <Resource Include="Resources\alliance_saveas.png" />
	  <Resource Include="Resources\alliance_translation.png" />
	</ItemGroup>

	<Target Name="RemoveModulePackageDir" AfterTargets="BeforeBuild">
		<!-- Clean folders before build -->
		<Exec Command="rmdir &quot;$(ProjectDir)\obj\$(ModuleName)\&quot; /s /q" />
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- Replace SubModule.xml version with $(AllianceVersion) version -->
		<Exec Command="powershell -Command &quot; $env:AllianceVersion = '$(AllianceVersion)'; $env:ProjectDir = '$(ProjectDir)'; $xml = [xml](Get-Content ($env:ProjectDir + '_Module\SubModule.xml')); $xml.SelectSingleNode('//Version').SetAttribute('value', 'v' + $env:AllianceVersion); $xml.Save($env:ProjectDir + '_Module\SubModule.xml')&quot;" />

		<!-- Copy Common module folders -->
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\Animations&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\Animations\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\Assets&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\Assets\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\AssetSources&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\AssetSources\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\GUI&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\GUI\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\ModuleData&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\ModuleData\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\ModuleSounds&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\ModuleSounds\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\Prefabs&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\Prefabs\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\Scenarios&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\Scenarios\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\SceneEditData&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\SceneEditData\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\SceneObj&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\SceneObj\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\Spawn_Presets&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\Spawn_Presets\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		<Exec Command="xcopy &quot;$(ProjectDir)\..\Alliance.Common\_Module\RuntimeDataCache&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\RuntimeDataCache\&quot; /E /C /I /Y /F" IgnoreExitCode="true" />
		
		<!-- Copy Editor-specific assets -->
		<Exec Command="xcopy &quot;$(ProjectDir)\_Module&quot; &quot;$(GameFolder)\Modules\$(ModuleName)&quot; /E /C /I /Y /F" />

		<!-- Copy dll into module -->
		<Exec Command="xcopy &quot;$(TargetPath)&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />

		<!-- Add other required dll -->
		<Exec Command="xcopy &quot;$(TargetDir)0Harmony.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)BehaviorTrees.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)BehaviorTreeWrapper.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)Alliance.Common.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)NAudio.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)NAudio.Asio.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)NAudio.Core.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)NAudio.Midi.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)NAudio.WinMM.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)NAudio.WinForms.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)NAudio.Wasapi.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />
		<Exec Command="xcopy &quot;$(TargetDir)Concentus.dll&quot; &quot;$(GameFolder)\Modules\$(ModuleName)\bin\Win64_Shipping_wEditor\&quot; /C /I /Y /F" />

	</Target>

</Project>