@echo off
echo ========================================
echo Generating Bannerlord PDB files
echo ========================================

REM Clean existing PDB folder
if exist .\BannerlordPDB rmdir /s /q .\BannerlordPDB
mkdir .\BannerlordPDB
mkdir .\BannerlordPDB\Core
mkdir .\BannerlordPDB\BirthAndDeath
mkdir .\BannerlordPDB\Native
mkdir .\BannerlordPDB\Multiplayer
mkdir .\BannerlordPDB\SandBox
mkdir .\BannerlordPDB\StoryMode

echo.
echo Step 1/3: Generating PDB files...
echo.

REM === Core Game DLLs (bin\Win64_Shipping_Client) ===
echo [Core Game]
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.AchievementSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.ActivitySystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.ViewModelCollection.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Core.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Core.ViewModelCollection.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Diamond.AccessProvider.GDK.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Diamond.AccessProvider.GOG.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Diamond.AccessProvider.Steam.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Diamond.AccessProvider.Test.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Diamond.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.DotNet.AutoGenerated.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.DotNet.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Engine.AutoGenerated.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Engine.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Engine.GauntletUI.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.Data.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.CodeGenerator.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.ExtraWidgets.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.PrefabSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Library.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.LinQuick.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.ModuleManager.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.AutoGenerated.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Diamond.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.GauntletUI.Widgets.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Helpers.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Launcher.Library.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Launcher.Steam.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.ViewModelCollection.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.NavigationSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Network.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.PlatformService.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.PlatformService.Epic.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.PlatformService.GOG.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.PlatformService.Steam.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.PlayerServices.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.PSAI.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.SaveSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.ScreenSystem.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.ServiceDiscovery.Client.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.Starter.Library.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.TwoDimension.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Core "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\TaleWorlds.TwoDimension.Standalone.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"

REM === BirthAndDeath Module ===
echo [BirthAndDeath Module]
ilspycmd -genpdb -o .\BannerlordPDB\BirthAndDeath "%BANNERLORD_GAME_DIR%\Modules\BirthAndDeath\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.ViewModelCollection.BirthAndDeath.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"

REM === Native Module ===
echo [Native Module]
ilspycmd -genpdb -o .\BannerlordPDB\Native "%BANNERLORD_GAME_DIR%\Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated.0.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Native "%BANNERLORD_GAME_DIR%\Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated.1.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Native "%BANNERLORD_GAME_DIR%\Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.GauntletUI.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Native "%BANNERLORD_GAME_DIR%\Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Platform.PC.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Native "%BANNERLORD_GAME_DIR%\Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.View.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"

REM === Multiplayer Module ===
echo [Multiplayer Module]
ilspycmd -genpdb -o .\BannerlordPDB\Multiplayer "%BANNERLORD_GAME_DIR%\Modules\Multiplayer\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.DedicatedCustomServer.ClientHelper.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Multiplayer "%BANNERLORD_GAME_DIR%\Modules\Multiplayer\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Multiplayer.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Multiplayer "%BANNERLORD_GAME_DIR%\Modules\Multiplayer\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Multiplayer.GauntletUI.AutoGenerated.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Multiplayer "%BANNERLORD_GAME_DIR%\Modules\Multiplayer\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Multiplayer.GauntletUI.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Multiplayer "%BANNERLORD_GAME_DIR%\Modules\Multiplayer\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Multiplayer.View.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\Multiplayer "%BANNERLORD_GAME_DIR%\Modules\Multiplayer\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Multiplayer.ViewModelCollection.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"

REM === SandBox Module ===
echo [SandBox Module]
ilspycmd -genpdb -o .\BannerlordPDB\SandBox "%BANNERLORD_GAME_DIR%\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\SandBox "%BANNERLORD_GAME_DIR%\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.GauntletUI.AutoGenerated.0.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\SandBox "%BANNERLORD_GAME_DIR%\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.GauntletUI.AutoGenerated.1.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\SandBox "%BANNERLORD_GAME_DIR%\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.GauntletUI.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\SandBox "%BANNERLORD_GAME_DIR%\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.View.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\SandBox "%BANNERLORD_GAME_DIR%\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.ViewModelCollection.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"

REM === StoryMode Module ===
echo [StoryMode Module]
ilspycmd -genpdb -o .\BannerlordPDB\StoryMode "%BANNERLORD_GAME_DIR%\Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\StoryMode "%BANNERLORD_GAME_DIR%\Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.GauntletUI.AutoGenerated.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\StoryMode "%BANNERLORD_GAME_DIR%\Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.GauntletUI.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\StoryMode "%BANNERLORD_GAME_DIR%\Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.View.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"
ilspycmd -genpdb -o .\BannerlordPDB\StoryMode "%BANNERLORD_GAME_DIR%\Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.ViewModelCollection.dll" --referencepath "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client"

echo.
echo Step 2/3: Cleaning up .csproj files...
del /q /s .\BannerlordPDB\*.csproj 2>nul

echo.
echo Step 3/3: Copying PDB files to game directory...
echo.

REM Copy PDB files using subdirectories
xcopy /Y /Q ".\BannerlordPDB\Core\*.pdb" "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\" 2>nul
xcopy /Y /Q ".\BannerlordPDB\BirthAndDeath\*.pdb" "%BANNERLORD_GAME_DIR%\Modules\BirthAndDeath\bin\Win64_Shipping_Client\" 2>nul
xcopy /Y /Q ".\BannerlordPDB\Native\*.pdb" "%BANNERLORD_GAME_DIR%\Modules\Native\bin\Win64_Shipping_Client\" 2>nul
xcopy /Y /Q ".\BannerlordPDB\Multiplayer\*.pdb" "%BANNERLORD_GAME_DIR%\Modules\Multiplayer\bin\Win64_Shipping_Client\" 2>nul
xcopy /Y /Q ".\BannerlordPDB\SandBox\*.pdb" "%BANNERLORD_GAME_DIR%\Modules\SandBox\bin\Win64_Shipping_Client\" 2>nul
xcopy /Y /Q ".\BannerlordPDB\StoryMode\*.pdb" "%BANNERLORD_GAME_DIR%\Modules\StoryMode\bin\Win64_Shipping_Client\" 2>nul

echo.
echo ========================================
echo PDB generation complete!
echo ========================================
echo.
echo PDB files copied to:
echo   - Game Core: "%BANNERLORD_GAME_DIR%\bin\Win64_Shipping_Client\"
echo   - BirthAndDeath: Modules\BirthAndDeath\bin\Win64_Shipping_Client\
echo   - Native: Modules\Native\bin\Win64_Shipping_Client\
echo   - Multiplayer: Modules\Multiplayer\bin\Win64_Shipping_Client\
echo   - SandBox: Modules\SandBox\bin\Win64_Shipping_Client\
echo   - StoryMode: Modules\StoryMode\bin\Win64_Shipping_Client\
echo.
pause